[package]
authors = ["Hendrik Sollich <hendrik@hoodie.de>"]
name = "jatt"
version = "0.1.0"
[dependencies]
error-chain = "0.11"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.7"
toml = "0.4"
